from __future__ import annotations

import json
from typing import Any, Optional

import httpx


class GeminiAPIError(Exception):
    """Raised when the Gemini API returns a non-success response or invalid data."""


def _extract_text_from_response(data: dict) -> Optional[str]:
    """Safely extract the first text part from the Gemini response JSON."""
    try:
        candidates = data.get("candidates") or []
        if not candidates:
            return None
        first_candidate = candidates[0] or {}
        content = first_candidate.get("content") or {}
        parts = content.get("parts") or []
        if not parts:
            return None
        first_part = parts[0] or {}
        text = first_part.get("text")
        if isinstance(text, str):
            return text
        return None
    except Exception:
        return None


# PUBLIC_INTERFACE
async def generate_reply(message: str, model: str, api_key: str) -> str:
    """Generate a reply from Google's Gemini API for the given message.

    Parameters:
        message: The user-provided message text.
        model: The Gemini model name, e.g., 'gemini-1.5-flash'.
        api_key: The API key to authenticate with the Gemini API.

    Returns:
        The reply text generated by the model.

    Raises:
        GeminiAPIError: If the API call fails or the response is invalid.
    """
    if not api_key:
        raise GeminiAPIError("Missing API key for Gemini (GEMINI_API_KEY).")

    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent"
    params = {"key": api_key}
    payload = {
        "contents": [
            {
                "parts": [
                    {"text": message},
                ]
            }
        ]
    }

    async with httpx.AsyncClient(timeout=30.0) as client:
        resp = await client.post(url, params=params, json=payload)
        if resp.status_code != 200:
            # Try to extract an error message
            try:
                err_json = resp.json()
                err_msg = json.dumps(err_json)
            except Exception:
                err_msg = resp.text
            raise GeminiAPIError(f"Gemini API error {resp.status_code}: {err_msg}")

        data: dict[str, Any] = resp.json()
        text = _extract_text_from_response(data)
        if not text or not text.strip():
            raise GeminiAPIError("Gemini API returned an empty or unparseable response.")
        return text.strip()
