from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


class SessionModel(BaseModel):
    """Represents a chat session with metadata."""

    id: str = Field(..., description="Unique identifier of the session.")
    title: str = Field(..., description="Human-friendly session title.")
    created_at: datetime = Field(..., description="UTC timestamp when the session was created.")


class MessageModel(BaseModel):
    """A single chat message stored in history."""

    id: str = Field(..., description="Unique identifier of the message.")
    role: str = Field(..., description="The role of the message sender, e.g., 'user' or 'assistant'.")
    content: str = Field(..., description="The message content.")
    timestamp: datetime = Field(..., description="UTC timestamp when the message was created.")


class ChatRequest(BaseModel):
    """Incoming request payload to send a message to the AI model."""

    session_id: str = Field(..., description="The session ID to associate this chat message with.")
    message: str = Field(..., description="The user message to send to the AI model.")
    stream: Optional[bool] = Field(
        False,
        description="Whether to stream the response. Not implemented; responses are non-streaming.",
    )


class ChatResponse(BaseModel):
    """Response payload returned after generating a reply from the AI model."""

    session_id: str = Field(..., description="The session ID used for this chat.")
    reply: str = Field(..., description="The assistant's reply generated by the AI model.")
    message_id: str = Field(..., description="The identifier of the assistant message that was stored.")
    timestamp: datetime = Field(..., description="UTC timestamp when the assistant message was created.")


class SessionCreateResponse(BaseModel):
    """Response after creating a new session."""

    session: SessionModel = Field(..., description="The newly created session resource.")


class SessionListResponse(BaseModel):
    """Response holding a list of available sessions."""

    sessions: List[SessionModel] = Field(..., description="All sessions available in the store.")


class HistoryResponse(BaseModel):
    """Response for a session's message history."""

    session_id: str = Field(..., description="The session ID corresponding to this history.")
    history: List[MessageModel] = Field(..., description="The list of messages in the session history.")


class ErrorResponse(BaseModel):
    """Error payload for standardized error responses."""

    detail: str = Field(..., description="Human-readable error detail.")
    code: Optional[str] = Field(None, description="Optional machine-readable error code.")
